apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-test-deployment
spec:
  selector:
    matchLabels:
      app: devops-test
  replicas: 1
  template:
    metadata:
      labels:
        app: devops-test
    spec:
      containers:
      - name: devops-test
        image: __DOCKER_REPOSITORY__/__IMAGE_NAME__:__IMAGE_TAG__
        ports:
        - containerPort: 5000
---
kind: Service
apiVersion: v1
metadata:
  name: devops-test-service
spec:
  selector:
    app: devops-test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer #NodePort
