apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-test-deployment
spec:
  selector:
    matchLabels:
      app: devops-test
  replicas: 1
  template:
    metadata:
      labels:
        app: devops-test
    spec:
      containers:
      - name: devops-test
        image: ghcr.io/matthewjstevens/f40dbcee:latest
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: dockerconfigjson-github-com
---
kind: Service
apiVersion: v1
metadata:
  name: devops-test-service
spec:
  selector:
    app: devopstest
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer #NodePort
