apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-test
  template:
    metadata:
      labels:
        app: devops-test
    spec:
      containers:
      - name: devops-test
        image: _DOCKER_REPOSITORY_:_IMAGE_TAG_
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
      #imagePullSecrets:
      #- name: dockerconfigjson-github-com
---
apiVersion: v1
kind: Service
metadata:
  name: devops-test
spec:
  selector:
    app: devops-test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30610
  type: NodePort
